# eureka:
#   client:
#     register-with-eureka: true
#     fetch-registry: true
    
#   instance:
#     hostname: localhost


# department:
#   url: saveDepartment

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: root
    password: root